# Generated by Django 2.2.6 on 2020-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200129_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.IntegerField(choices=[(1, 'Высокий приоритет'), (2, 'Средний приоритет'), (3, 'Низкий приоритет')], default=2, verbose_name='Приоритет'),
        ),
    ]
