# Generated by Django 2.2.6 on 2020-01-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200129_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('HP', 'Высокий приоритет'), ('MP', 'Средний приоритет'), ('LP', 'Низкий приоритет')], default='MP', max_length=2),
        ),
    ]
