# Generated by Django 2.2.6 on 2020-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200129_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('HIGH_PRIORITY', 'Высокий приоритет'), ('MEDIUM_PRIORITY', 'Средний приоритет'), ('LOW_PRIORITY', 'Низкий приоритет')], default='MEDIUM_PRIORITY', max_length=100),
        ),
    ]
