# Generated by Django 2.2.6 on 2020-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20200129_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('High Priority', 'Высокий приоритет'), ('Medium Priority', 'Средний приоритет'), ('Low Priority', 'Низкий приоритет')], default='Medium Priority', max_length=100),
        ),
    ]
